FROM ubuntu:bionic

WORKDIR /root

ADD https://deb.frrouting.org/frr/keys.asc ./

RUN apt-get update && apt-get install -y --no-install-suggests --no-install-recommends gpg ca-certificates gpg-agent &&\
    apt-key add keys.asc && rm -rf keys.asc &&\
    echo deb https://deb.frrouting.org/frr bionic frr-stable | tee -a /etc/apt/sources.list.d/frr.list &&\
    sed -i 's:^path-exclude=/usr/share/man:#path-exclude=/usr/share/man:' /etc/dpkg/dpkg.cfg.d/excludes &&\
    apt-get update && env DEBIAN_FRONTEND=noninteractive\
    apt-get install -y --no-install-suggests --no-install-recommends\
    language-pack-es\
    man-db\
    manpages-es\
    manpages-posix\
    apache2\
    bind9\
    bridge-utils\
    command-not-found\
    bash-completion\
    dnsutils\
    ethtool\
    frr\
    frr-doc\
    frr-pythontools\
    frr-rpki-rtrlib\
    frr-snmp\
    ifupdown\
    iperf\
    iputils-arping\
    iputils-clockdiff\
    iputils-ping\
    iputils-tracepath\
    iptables\
    isc-dhcp-server\
    isc-dhcp-client\
    isc-dhcp-relay\
    isc-dhcp-common\
    lsof\
    less\
    mtr\
    net-tools\
    netcat\
    nmap\
    python3\
    ssh\
    sudo\
    vim\
    nano\
    mc\
    tcpdump\
    telnet\
    traceroute\
    vlan\
    whois\
    wget\
    curl\
    radvd\
    #wireshark\
    #lxde\
    &&\
    rm -r /usr/lib/locale/* &&\
    echo "es_NI.UTF-8 UTF-8" > /var/lib/locales/supported.d/es &&\
    echo -e "LANG=\"es_NI.UTF-8\"\nLANGUAGE=\"es_NI:es\"" >> /etc/default/locale &&\
    locale-gen --purge &&\
    apt-get remove --autoremove -y hicolor-icon-theme &&\
    rm -rf /var/lib/apt/lists/* /etc/apt/apt.conf.d/docker-clean

ENV LANG es_NI.UTF-8
ENV LANGUAGE es_NI:es 
ENV LC_ALL es_NI.UTF-8
ENV PROMPT_COMMAND 'history -a'
ENV TERM xterm-256color
RUN echo "by: Srealmoreno" > .bash_history
RUN sed -i "17,32s/no/yes/" /etc/frr/daemons
RUN sed -i "46s/.//"        /etc/skel/.bashrc 
RUN sed -i "35,41s/.//"     /etc/bash.bashrc
RUN sed -i "39b0; 97,99b0; b ;:0 ;s/.//" .bashrc >> .bashrc && echo "stty -ixon\n\ncd \$PWD\n\nif [ -n \"\$IPv6_Hosts\" ] && [ -f ~/.etc/hosts ]; then\n\tcat ~/.etc/hosts >> /etc/hosts\n\tunset IPv6_Hosts\nfi\n\nifdown -a >/dev/null 2>/dev/null\n\nif [ -f ~/.etc/radvd.conf ]; then\n\tln -s ~/.etc/radvd.conf /etc/\nfi\n\nif [ -f ~/\$(hostname).startup ]; then\n\tbash ~/\$(hostname).startup\nfi\n\ngrep -oP '^\s*auto\s+\K.+' /etc/network/interfaces | while read dev; do\n\tip link set dev \$dev up\ndone\n\nifup -a\n\nchown -R 1000:1000 /etc/default /etc/network /etc/dhcp /root /save 2>/dev/null\n\nchown 1000:1000 /etc 2>/dev/null" >> .bashrc
RUN useradd --create-home --shell /bin/bash --groups sudo --uid 1000 anfitrion

CMD [ "bash" ]

#CMD [ "startlxde" ]

# Para tener entorno gráfico:
# Descomentar Wireshark y lxde
# Comentar 'CMD[ "bash" ]'
# Descomentar '#CMD[ "startlxde" ]
